version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app_network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: always
    networks:
      - app_network

  producer:
    build: ./producer
    container_name: producer
    env_file: ./producer/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - app_network

volumes:
  rabbitmq_data:
    driver: local
  mongo_data:
    driver: local

networks:
  app_network:
    driver: bridge
