version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
  backend:
    build: ./backend
    ports: ["3000:3000"]
    env_file: ./backend/.env
    depends_on:
      - rabbitmq
      - mongo
  producer:
    build: ./producer
    env_file: ./producer/.env
    depends_on:
      - rabbitmq
